export const ADD_USER_ACTION = 'ADD_USER_ACTION';
export const DELETE_USER_ACTION = 'DELETE_USER_ACTION';
export const FILTER_USER_ACTION = 'FILTER_USER_ACTION';
export const SORT_USER_ACTION = 'SORT_USER_ACTION';
